- hosts: all
  order: sorted
  become: yes
  gather_facts: yes

  tasks:
#    - name: Enable Systemd-networkd
#      ansible.builtin.systemd:
#        name: systemd-networkd
#        state: started
#        enabled: yes

    - name: Set parameters for vlan 10
      ansible.builtin.set_fact:
        vlan_ip: 2
        vlan_dev: eth1
        onemore_vlan: '0'

    - name: Configuration VLAN on client
      block:
        - name: Set parameters for vlan 11
          ansible.builtin.set_fact:
            vlan_id: 11

        - name: Generate vlan.netdev file
          ansible.builtin.template:
            src: vlan.netdev.j2
            dest: /etc/systemd/network/10-vlan{{vlan_id}}.netdev

        - name: Generate vlan.network file
          ansible.builtin.template:
            src: vlan.network.j2
            dest: /etc/systemd/network/10-vlan{{vlan_id}}.network

        - name: Generate ethX.network file
          ansible.builtin.template:
            src: eth.network.j2
            dest: /etc/systemd/network/10-{{vlan_dev}}.network
      when: ansible_hostname == 'client1'

    - name: Configuration VLAN on Server
      block:
        - name: Set parameters for vlan 10
          ansible.builtin.set_fact:
            vlan_id: 10

        - name: Generate vlan.netdev file
          ansible.builtin.template:
            src: vlan.netdev.j2
            dest: /etc/systemd/network/10-vlan{{vlan_id}}.netdev

        - name: Generate vlan.network file
          ansible.builtin.template:
            src: vlan.network.j2
            dest: /etc/systemd/network/10-vlan{{vlan_id}}.network

        - name: Generate ethX.network file
          ansible.builtin.template:
            src: eth.network.j2
            dest: /etc/systemd/network/10-{{vlan_dev}}.network
      when: ansible_hostname == 'server1'

    - name: Restart Systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd
        state: restarted
        enabled: yes
